version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    branches:
      only:
        - master
        - devel
    steps:
      - checkout
      # Install eslint explicitly because some dev dependencies are private
      - run: npm install eslint babel-eslint
      - run: npm run lint
