version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      # Install eslint explicitly because some dev dependencies are private
      - run: npm install eslint
      - run: npm run lint
