version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      # Install eslint explicitly because some dev dependencies are private
      - run: npm install eslint babel-eslint
      - run: npm run lint
# Experimental setting: per-branch notifications, based on:
# https://circleci.com/docs/1.0/configuration/#per-branch-notifications
# https://discuss.circleci.com/t/only-notify-for-some-branches/10244/6
experimental:
  notify:
    branches:
      only:
        - master
        - devel
